# Rename mtDNA
vips_mtDNA[1,3] <- "Roman the Great"
vips_mtDNA[2,3] <- "Peter II of Russia"
vips_mtDNA[3,3] <- "Nicholas II"
vips_mtDNA[4,3] <- "Maria Feodorovna (Dagmar of Denmark)"
vips_mtDNA[5,3] <- "Alexandra Feodorovna (Alix of Hesse)"
vips_mtDNA[6,3] <- "George I of Greece"
vips_mtDNA[7,3] <- "Sophia of Prussia"
vips_mtDNA[8,3] <- "Princess Alice of Battenberg"
vips_mtDNA[9,3] <- "Alexander of Greece"
vips_mtDNA[10,3] <- "George II of Greece"
vips_mtDNA[11,3] <- "Paul of Greece"
vips_mtDNA[12,3] <- "Queen Anne-Marie of Greece"
vips_mtDNA[13,3] <- "Pavlos, Crown Prince of Greece"
vips_mtDNA[14,3] <- "Ferdinand I of Romania"
vips_mtDNA[15,3] <- "Michael I of Romania"
vips_mtDNA[16,3] <- "Bolesław I the Brave"
vips_mtDNA[17,3] <- "Catherine of Austria, Queen of Poland"
vips_mtDNA[18,3] <- "Anne of Austria, Queen of Poland"
vips_mtDNA[19,3] <- "Władysław IV Vasa"
vips_mtDNA[20,3] <- "Constance of Austria"
vips_mtDNA[21,3] <- "John II Casimir Vasa"
vips_mtDNA[22,3] <- "Eleonore of Austria, Queen of Poland"
vips_mtDNA[23,3] <- "Elizabeth of Austria (1436–1505)"
vips_mtDNA[24,3] <- "John I Albert"
vips_mtDNA[25,3] <- "Alexander Jagiellon"
vips_mtDNA[26,3] <- "Sigismund I the Old"
vips_mtDNA[27,3] <- "Marie Louise Gonzaga"
vips_mtDNA[28,3] <- "Marie Thérèse de Bourbon"
vips_mtDNA[29,3] <- "Maria II of Portugal"
vips_mtDNA[30,3] <- "Pedro V of Portugal"
vips_mtDNA[31,3] <- "Luís I of Portugal"
vips_mtDNA[32,3] <- "Philip I of Castile"
vips_mtDNA[33,3] <- "Margaret of Austria, Queen of Spain"
vips_mtDNA[34,3] <- "Philip IV of Spain"
vips_mtDNA[35,3] <- "Elisabeth of France, Queen of Spain"
vips_mtDNA[36,3] <- "Mariana of Austria"
vips_mtDNA[37,3] <- "Charles II of Spain"
vips_mtDNA[38,3] <- "Marie Louise d'Orléans"
vips_mtDNA[39,3] <- "Maria Luisa of Savoy"
vips_mtDNA[40,3] <- "Ferdinand VI"
vips_mtDNA[41,3] <- "Isabella II"
vips_mtDNA[42,3] <- "Alfonso XII"
vips_mtDNA[43,3] <- "Victoria Eugenie of Battenberg"
vips_mtDNA[44,3] <- "Queen Sofía of Spain"
vips_mtDNA[45,3] <- "Felipe VI of Spain"
vips_mtDNA[46,3] <- "Maria Amalia of Saxony"
vips_mtDNA[47,3] <- "Charles IV of Spain"
vips_mtDNA[48,3] <- "Maria Josepha Amalia of Saxony"
vips_mtDNA[49,3] <- "Charles Emmanuel III"
vips_mtDNA[50,3] <- "Maria Cristina of Naples and Sicily"
vips_mtDNA[51,3] <- "Maria Theresa of Austria, Queen of Sardinia"
vips_mtDNA[52,3] <- "Victor Emmanuel II"
vips_mtDNA[53,3] <- "Joanna of Austria, Grand Duchess of Tuscany"
vips_mtDNA[54,3] <- "Ferdinando II de' Medici"
vips_mtDNA[55,3] <- "Ingeborg of Denmark, Queen of France"
vips_mtDNA[56,3] <- "Francis I of France"
vips_mtDNA[57,3] <- "Henry IV of France"
vips_mtDNA[58,3] <- "Marie de' Medici"
vips_mtDNA[59,3] <- "Louis XIII"
vips_mtDNA[60,3] <- "Maria Theresa of Spain"
vips_mtDNA[61,3] <- "Louis, Grand Dauphin"
vips_mtDNA[62,3] <- "Louis XV"
vips_mtDNA[63,3] <- "Louis XVI"
vips_mtDNA[64,3] <- "Louis XVIII"
vips_mtDNA[65,3] <- "Charles X of France"
vips_mtDNA[66,3] <- "Marie Antoinette"
vips_mtDNA[67,3] <- "Louis XVII"
vips_mtDNA[68,3] <- "Marie Louise, Duchess of Parma"
vips_mtDNA[69,3] <- "Maria Amalia of Naples and Sicily"
vips_mtDNA[70,3] <- "Leopold I of Belgium"
vips_mtDNA[71,3] <- "Louise of Orléans"
vips_mtDNA[72,3] <- "Leopold II of Belgium"
vips_mtDNA[73,3] <- "Charlotte of Belgium"
vips_mtDNA[74,3] <- "William I of the Netherlands"
vips_mtDNA[75,3] <- "Maurice, Prince of Orange"
vips_mtDNA[76,3] <- "Frederick Augustus II of Saxony"
vips_mtDNA[77,3] <- "John, King of Saxony"
vips_mtDNA[78,3] <- "Frederick William I of Prussia"
vips_mtDNA[79,3] <- "Elisabeth Christine of Brunswick-Wolfenbüttel-Bevern"
vips_mtDNA[80,3] <- "Frederick William II of Prussia"
vips_mtDNA[81,3] <- "Victoria, Princess Royal"
vips_mtDNA[82,3] <- "Wilhelm II"
vips_mtDNA[83,3] <- "Boleslaus II, Duke of Bohemia"
vips_mtDNA[84,3] <- "Anne of Bohemia and Hungary"
vips_mtDNA[85,3] <- "Ferdinand IV, King of the Romans"
vips_mtDNA[86,3] <- "Henry of Bohemia"
vips_mtDNA[87,3] <- "Rudolf I of Bohemia"
vips_mtDNA[88,3] <- "Joanna of Bavaria"
vips_mtDNA[89,3] <- "Albert II of Germany"
vips_mtDNA[90,3] <- "Elizabeth of Luxembourg"
vips_mtDNA[91,3] <- "Vladislaus II of Hungary"
vips_mtDNA[92,3] <- "Elizabeth Stuart, Queen of Bohemia"
vips_mtDNA[93,3] <- "Maria Amalia, Holy Roman Empress"
vips_mtDNA[94,3] <- "Maria Luisa of Spain"
vips_mtDNA[95,3] <- "Louis II, Duke of Bavaria"
vips_mtDNA[96,3] <- "Henry XIII, Duke of Bavaria"
vips_mtDNA[97,3] <- "William II, Duke of Bavaria"
vips_mtDNA[98,3] <- "Albert II, Duke of Bavaria"
vips_mtDNA[99,3] <- "John III, Duke of Bavaria"
vips_mtDNA[100,3] <- "Louis IX, Duke of Bavaria"
vips_mtDNA[101,3] <- "Elisabeth of Bavaria, Queen of Germany"
vips_mtDNA[102,3] <- "Elisabeth of Carinthia, Queen of the Romans"
vips_mtDNA[103,3] <- "Frederick the Fair"
vips_mtDNA[106,3] <- "Barbara of Cilli" 
vips_mtDNA[107,3] <- "Maximilian II, Holy Roman Emperor"
vips_mtDNA[108,3] <- "Ferdinand II, Holy Roman Emperor"
vips_mtDNA[109,3] <- "Leopold I, Holy Roman Emperor"
vips_mtDNA[111,3] <- "Maria Josepha of Bavaria"
vips_mtDNA[113,3] <- "Francis II, Holy Roman Emperor"
vips_mtDNA[114,3] <- "Leopold II, Holy Roman Emperor"
vips_mtDNA[115,3] <- "Rudolf I of Bohemia"
vips_mtDNA[117,3] <- "Leopold I, Duke of Austria"
vips_mtDNA[118,3] <- "Albert II, Duke of Austria"
vips_mtDNA[119,3] <- "Otto, Duke of Austria"
vips_mtDNA[121,3] <- "Maria Theresa"
vips_mtDNA[122,3] <- "Joseph II, Holy Roman Emperor"
vips_mtDNA[123,3] <- "Ferdinand I of Austria"
vips_mtDNA[124,3] <- "Maria Leopoldina of Austria"
vips_mtDNA[126,3] <- "Charles I of Austria"
vips_mtDNA[127,3] <- "Richeza of Poland, Queen of Sweden"
vips_mtDNA[128,3] <- "Valdemar, King of Sweden"
vips_mtDNA[129,3] <- "Magnus III of Sweden"
vips_mtDNA[130,3] <- "Gustavus Adolphus"
vips_mtDNA[131,3] <- "Charles X Gustav"
vips_mtDNA[132,3] <- "Olof Skötkonung"
vips_mtDNA[133,3] <- "Christina, Queen of Sweden"
vips_mtDNA[134,3] <- "Princess Margaret of Connaught"
vips_mtDNA[135,3] <- "Louise Mountbatten"
vips_mtDNA[136,3] <- "Ingrid of Sweden"
vips_mtDNA[137,3] <- "Carl XVI Gustaf"
vips_mtDNA[138,3] <- "Rikissa Birgersdotter"
vips_mtDNA[139,3] <- "Olav V"
vips_mtDNA[140,3] <- "Sigrid the Haughty"
vips_mtDNA[141,3] <- "Harald II of Denmark"
vips_mtDNA[142,3] <- "Cnut"
vips_mtDNA[143,3] <- "Sweyn II of Denmark"
vips_mtDNA[144,3] <- "Margrethe II"
vips_mtDNA[145,3] <- "Canute V of Denmark"
vips_mtDNA[146,3] <- "Sophia of Minsk"
vips_mtDNA[147,3] <- "Canute VI of Denmark"
vips_mtDNA[148,3] <- "Valdemar II of Denmark"
vips_mtDNA[149,3] <- "Richeza of Denmark"
vips_mtDNA[151, 3] <- "Anne of Denmark"
vips_mtDNA[152, 3] <- "Christian III of Denmark"
vips_mtDNA[153, 3] <- "Christian IV of Denmark"
vips_mtDNA[154, 3] <- "Frederick VI of Denmark"
vips_mtDNA[155, 3] <- "Christian VIII of Denmark"
vips_mtDNA[156, 3] <- "Frederick VIII of Denmark"
vips_mtDNA[157, 3] <- "Juliana Maria of Brunswick-Wolfenbüttel"
vips_mtDNA[158, 3] <- "James III of Scotland"
vips_mtDNA[159, 3] <- "Charles I of England"
vips_mtDNA[160, 3] <- "George I of Great Britain"
vips_mtDNA[161, 3] <- "George III of the United Kingdom"
vips_mtDNA[162, 3] <- "Alexandra of Denmark"
vips_mtDNA[163, 3] <- "George V"
vips_mtDNA[164, 3] <- "Henrietta Maria"
vips_mtDNA[165, 3] <- "Charles II of England"
vips_mtDNA[166, 3] <- "James II of England"
vips_mtDNA[167, 3] <- "William III of England"
vips_mtDNA[168, 3] <- "Queen Victoria"
vips_mtDNA[169, 3] <- "Edward VII"
vips_mtDNA[170, 3] <- "Prince Philip, Duke of Edinburgh"
vips_mtDNA[171, 3] <- "Edward IV of England"
vips_mtDNA[172, 3] <- "Richard III of England"
vips_mtDNA[173, 3] <- "Prince William, Duke of Cambridge"
vips_mtDNA[174, 3] <- "Napoleon"
vips_mtDNA[175, 3] <- "Napoleon II"
vips_mtDNA[176, 3] <- "Birger Jarl"
vips_mtDNA[177, 3] <- "Erik, son of Birger"
vips_mtDNA[178, 3] <- "Mechtild of Holstein"

# Remove duplicate names 
vips_mtDNA <- vips_mtDNA[-c(104,105,110,112,116,120,125), ]

# Rename yDNA
vips_yDNA[1, 3] <- "Ramesses III"
vips_yDNA[2, 3] <- "Leopold I, Margrave of Austria"
vips_yDNA[3, 3] <- "Henry I, Margrave of Austria"
vips_yDNA[4, 3] <- "Adalbert, Margrave of Austria"
vips_yDNA[5, 3] <- "Ernest, Margrave of Austria"
vips_yDNA[6, 3] <- "Leopold II, Margrave of Austria"
vips_yDNA[7, 3] <- "Leopold III, Margrave of Austria"
vips_yDNA[8, 3] <- "Leopold, Duke of Bavaria"
vips_yDNA[9, 3] <- "Henry II, Duke of Austria"
vips_yDNA[10, 3] <- "Leopold V, Duke of Austria"
vips_yDNA[11, 3] <- "Frederick I, Duke of Austria"
vips_yDNA[12, 3] <- "Leopold VI, Duke of Austria"
vips_yDNA[13, 3] <- "Frederick II, Duke of Austria"
vips_yDNA[16, 3] <- "Gospatric, Earl of Northumbria"
vips_yDNA[17, 3] <- "Earl of Home"
vips_yDNA[20, 3] <- "Clan Donald"
vips_yDNA[21, 3] <- "Clan MacDougall"
vips_yDNA[22, 3] <- "Clan Swinton"
vips_yDNA[23, 3] <- "Olaf II of Denmark"
vips_yDNA[24, 3] <- "Christian I of Denmark"
vips_yDNA[25, 3] <- "John, King of Denmark"
vips_yDNA[26, 3] <- "Christian II of Denmark"
vips_yDNA[27, 3] <- "Frederick I of Denmark"
vips_yDNA[28, 3] <- "Christian III of Denmark"
vips_yDNA[29, 3] <- "Frederick II of Denmark"
vips_yDNA[30, 3] <- "Christian IV of Denmark"
vips_yDNA[31, 3] <- "Frederick III of Denmark"
vips_yDNA[32, 3] <- "Christian V of Denmark"
vips_yDNA[33, 3] <- "Frederick IV of Denmark"
vips_yDNA[34, 3] <- "Christian VI of Denmark"
vips_yDNA[35, 3] <- "Frederick V of Denmark"
vips_yDNA[36, 3] <- "Christian VII of Denmark"
vips_yDNA[37, 3] <- "Frederick VI of Denmark"
vips_yDNA[38, 3] <- "Christian VIII of Denmark"
vips_yDNA[39, 3] <- "Frederick VII of Denmark"
vips_yDNA[40, 3] <- "Christian IX of Denmark"
vips_yDNA[41, 3] <- "Frederick VIII of Denmark"
vips_yDNA[42, 3] <- "Christian X of Denmark"
vips_yDNA[43, 3] <- "Frederick IX of Denmark"
vips_yDNA[44, 3] <- "Richard III of England"
vips_yDNA[45, 3] <- "Prince Philip, Duke of Edinburgh"
vips_yDNA[46, 3] <- "Charles III"
vips_yDNA[47, 3] <- "William, Prince of Wales"
vips_yDNA[48, 3] <- "Birger Jarl"
vips_yDNA[49, 3] <- "Eric Birgersson"
vips_yDNA[50, 3] <- "Emperor Higashiyama"
vips_yDNA[51, 3] <- "Napoleon"
vips_yDNA[52, 3] <- "Napoleon III"
vips_yDNA[53, 3] <- "Nelson Mandela"
vips_yDNA[54, 3] <- "Lyndon B. Johnson"
vips_yDNA[55, 3] <- "David Attenborough"
vips_yDNA[56, 3] <- "Richard Attenborough"
vips_yDNA[57, 3] <- "Orville Wright"
vips_yDNA[58, 3] <- "Wilbur Wright"
vips_yDNA[59, 3] <- "Albert Einstein"
vips_yDNA[60, 3] <- "Joseph Stalin"
vips_yDNA[61, 3] <- "Leo Tolstoy"
vips_yDNA[62, 3] <- "Warren Buffett"
vips_yDNA[63, 3] <- "Alexander Hamilton"
vips_yDNA[64, 3] <- "Calvin Coolidge"
vips_yDNA[65, 3] <- "Bill Clinton"
vips_yDNA[66, 3] <- "Sting"
vips_yDNA[67, 3] <- "Martin Luther"
vips_yDNA[68, 3] <- "Novak Djokovic"
vips_yDNA[69, 3] <- "Duke of Hamilton"
vips_yDNA[70, 3] <- "Henry Luce"
vips_yDNA[71, 3] <- "Myles Standish"
vips_yDNA[72, 3] <- "Paul Reynaud"
vips_yDNA[73, 3] <- "Max von Sydow"
vips_yDNA[74, 3] <- "Tom Hanks"
vips_yDNA[75, 3] <- "John Adams"
vips_yDNA[76, 3] <- "John Quincy Adams"
vips_yDNA[77, 3] <- "Ulysses S. Grant"
vips_yDNA[78, 3] <- "William McKinley"
vips_yDNA[79, 3] <- "Woodrow Wilson"
vips_yDNA[80, 3] <- "Che Guevara"
vips_yDNA[81, 3] <- "Charles Darwin"
vips_yDNA[82, 3] <- "Louis XVI"
vips_yDNA[83, 3] <- "Henry IV of France"
vips_yDNA[84, 3] <- "Fujiwara no Kamatari"
vips_yDNA[85, 3] <- "Sviatopolk I of Kyiv"
vips_yDNA[86, 3] <- "George I of Greece"
vips_yDNA[87, 3] <- "Constantine I of Greece"
vips_yDNA[88, 3] <- "Alexander of Greece"
vips_yDNA[89, 3] <- "George II of Greece"
vips_yDNA[90, 3] <- "Rhys Gethin"
vips_yDNA[91, 3] <- "Haakon VI"
vips_yDNA[92, 3] <- "Haakon VII"
vips_yDNA[93, 3] <- "Olav V"
vips_yDNA[94, 3] <- "Harald V of Norway"
vips_yDNA[95, 3] <- "Fath-Ali Shah Qajar"
vips_yDNA[96, 3] <- "Bořivoj I, Duke of Bohemia"
vips_yDNA[97, 3] <- "Spytihněv I, Duke of Bohemia"
vips_yDNA[98, 3] <- "Vratislaus I, Duke of Bohemia"
vips_yDNA[99, 3] <- "Wenceslaus I, Duke of Bohemia"
vips_yDNA[100, 3] <- "Boleslaus I, Duke of Bohemia"
vips_yDNA[101, 3] <- "Boleslaus II, Duke of Bohemia"
vips_yDNA[102, 3] <- "Boleslaus III, Duke of Bohemia"
vips_yDNA[103, 3] <- "Paul I of Russia"
vips_yDNA[104, 3] <- "Alexander I of Russia"
vips_yDNA[105, 3] <- "Grand Duke Konstantin Pavlovich of Russia"
vips_yDNA[106, 3] <- "Nicholas I of Russia"
vips_yDNA[107, 3] <- "Alexander II of Russia"
vips_yDNA[108, 3] <- "Alexander III of Russia"
vips_yDNA[109, 3] <- "Nicholas II"
vips_yDNA[110, 3] <- "Earl of Eglinton"
vips_yDNA[111, 3] <- "Somerled"
vips_yDNA[112, 3] <- "Valdemar, King of Sweden"
vips_yDNA[113, 3] <- "Magnus III of Sweden"
vips_yDNA[114, 3] <- "Birger, King of Sweden"
vips_yDNA[115, 3] <- "Valdemar, Duke of Finland"
vips_yDNA[116, 3] <- "Magnus IV of Sweden"
vips_yDNA[117, 3] <- "Eric XII of Sweden"

# Remove duplicate names
vips_yDNA <- vips_yDNA[-c(118:121), ]
vips_yDNA <- vips_yDNA[-c(14,15,18,19),]





